# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true
excerpt_separator:   "<!-- more -->"

# Setup
title:               SurAnand
tagline:             ':: My (Git-) Pushed Thoughts!'
description:         'I am Anand Surampudi. I speak my mind.'
url:                 http://github.com/SurAnand/asinode.github.io
baseurl:             ''
paginate:            5
comments:	     true

# About/contact
author:
  name:              Anand Surampudi
  url:               http://in.linkedin.com/in/suranand
  email:             suranands@gmail.com

# Custom vars
version:             1.0.0
