# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               AS Mind
tagline:             'I am Anand Surampudi. I speak my Mind.'
description:         'My (Git-) Pushed Thoughts.'
url:                 http://suranand.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Anand Surampud
  url:               https://twitter.com/suranands
  email:             suranands@gmail.com

# Custom vars
version:             1.0.0
