# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
excerpt_separator:   "<!-- more -->"

# Setup
title:               Anand's Space
tagline:             ':: My Studio of Thoughts!'
description:         'I am Anand Surampudi. I treasure my learnings here.'
url:                 http://github.com/suranands/suranands.github.io
baseurl:             ''
gems:		     [jekyll-paginate]
paginate:            5
paginate_path: 	     "page:num"
comments:	     true

# About/contact
author:
  name:              Anand Surampudi
  url:               https://www.linkedin.com/in/surab/
  email:             abs@outlook.in

# Custom vars
version:             2.0.0
