# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
excerpt_separator:   "<!-- more -->"

# Setup
title:               as inode
tagline:             ':: My Information Node!'
description:         'I am Anand Surampudi. I treasure my new learnings here.'
url:                 http://github.com/asinode/asinode.github.io
baseurl:             ''
gems:		     [jekyll-paginate]
paginate:            5
paginate_path: 	     "page:num"
comments:	     true

# About/contact
author:
  name:              Anand Surampudi
  url:               http://in.linkedin.com/in/asinode
  email:             asinode@zoho.com

# Custom vars
version:             1.0.0
