# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               AS Mind
tagline:             I am Anand Surampudi. I speak my Mind.
url:                 http://suranand.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Anand Surampudi
  url:               https://twitter.com/suranands
  email:             suranands@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/suranand
